weba:
  build: ./web
  expose:
    - 80

webb:
  build: ./web
  expose:
    - 80

webc:
  build: ./web
  expose:
    - 80

webd:
  build: ./web
  expose:
    - 80

webe:
  build: ./web
  expose:
    - 80

haproxy:
  image: haproxy:latest
  volumes:
    - /root/www/compose-haproxy-web/haproxy:/haproxy-override
    - /root/www/compose-haproxy-web/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  links:
    - weba
    - webb
    - webc
    - webd
    - webe
  ports:
    - "80:80"
    - "70:70"
  expose:
    - "80"
    - "70"
